version: '3.8'

services:
  # service base de donnees mariadb
  db:
    image: mariadb:10.6
    container_name: edutrack_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: edutrack_db
      MYSQL_USER: edutrack_user
      MYSQL_PASSWORD: userpassword
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: